# Generated by Django 5.2.5 on 2025-09-01 07:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/')),
                ('description', models.TextField(blank=True)),
                ('ranking_global', models.PositiveIntegerField(blank=True, null=True)),
                ('ranking_national', models.PositiveIntegerField(blank=True, null=True)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('student_population', models.PositiveIntegerField(blank=True, null=True)),
                ('acceptance_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('filters_applied', models.JSONField(blank=True, default=dict)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'search_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('level', models.CharField(choices=[('bachelor', "Bachelor's"), ('master', "Master's"), ('phd', 'PhD'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], max_length=20)),
                ('field_of_study', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('duration_value', models.PositiveIntegerField()),
                ('duration_unit', models.CharField(choices=[('months', 'Months'), ('years', 'Years'), ('weeks', 'Weeks')], default='years', max_length=10)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('application_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('admission_requirements', models.TextField(blank=True)),
                ('language_requirements', models.TextField(blank=True)),
                ('prerequisites', models.TextField(blank=True)),
                ('career_prospects', models.TextField(blank=True)),
                ('course_url', models.URLField(blank=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('is_part_time', models.BooleanField(default=False)),
                ('credits', models.PositiveIntegerField(blank=True, null=True)),
                ('gpa_requirement', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('is_active', models.BooleanField(default=True)),
                ('popularity_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.university')),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['-popularity_score', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UniversityContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admissions_email', models.EmailField(blank=True, max_length=254)),
                ('admissions_phone', models.CharField(blank=True, max_length=20)),
                ('international_office_email', models.EmailField(blank=True, max_length=254)),
                ('international_office_phone', models.CharField(blank=True, max_length=20)),
                ('financial_aid_email', models.EmailField(blank=True, max_length=254)),
                ('financial_aid_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('university', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='courses.university')),
            ],
            options={
                'db_table': 'university_contacts',
            },
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_reviews',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='SavedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_courses',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['level', 'field_of_study'], name='courses_level_f84327_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['tuition_fee'], name='courses_tuition_d115c3_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['university', 'level'], name='courses_univers_8d25f4_idx'),
        ),
    ]
